local M = {}

function M.highlight(aspects, opts)
  local background = opts.transparent and aspects.none or aspects.raven

  return {
    Bold = { bold = true },
    BufferLineBufferSelected = {
      bold = true,
      cterm = {
        bold = true,
        italic = true,
      },
      default = true,
      bg = background,
      fg = aspects.frost,
      italic = false,
    },
    Changed = {
      fg = aspects.sign_change,
    },
    Character = { fg = aspects.green },
    ColorColumn = { bg = aspects.coal },
    Comment = vim.tbl_extend("force", { fg = aspects.ash }, opts.styles.comments),
    Conceal = { fg = aspects.frost },
    Conditional = { fg = aspects.moss },
    Constant = { fg = aspects.snow },
    CopilotSuggestion = {
      link = "Comment",
    },
    CurSearch = { fg = aspects.coal, bg = aspects.bright_orange, bold = true },
    Cursor = { fg = aspects.cursor_fg, bg = aspects.cursor_bg },
    CursorColumn = { bg = aspects.coal },
    CursorIM = { fg = aspects.cursor_fg, bg = aspects.cursor_bg },
    CursorLine = {
      bg = aspects.coal,
    },
    CursorLineNr = {
      fg = aspects.gravel,
      bold = true,
    },
    Debug = { fg = aspects.bark },
    Define = { fg = aspects.bark },
    Delimiter = { fg = aspects.snow },
    DiagnosticFloatingError = { fg = aspects.error },
    DiffAdd = { bg = aspects.accent_green },
    DiffChange = {
      fg = aspects.sign_change,
      bg = aspects.accent_blue,
    },
    DiffDelete = { fg = aspects.sign_delete, bg = aspects.accent_red },
    DiffText = { fg = aspects.frost, bg = aspects.granite },
    Directory = { fg = aspects.green },
    EndOfBuffer = { fg = aspects.slate },
    Error = { fg = aspects.error, bg = aspects.raven, bold = true },
    ErrorMsg = { fg = aspects.frost, bg = background, bold = true },
    FloatBorder = { fg = aspects.ash },
    FoldColumn = { fg = aspects.gravel, bg = aspects.coal },
    Folded = { fg = aspects.gravel, bg = aspects.coal },
    Function = vim.tbl_extend("force", { fg = aspects.leaf }, opts.styles.functions),
    gitCommitComment = { fg = aspects.ash },
    gitCommitDiscardedFile = { fg = aspects.stone },
    gitCommitDiscardedType = { fg = aspects.stone },
    gitCommitHeader = { fg = aspects.ash },
    gitCommitSelectedFile = { fg = aspects.lichen },
    gitCommitSelectedType = { fg = aspects.lichen },
    gitCommitSummary = { fg = aspects.frost },
    Identifier = { fg = aspects.snow },
    Ignore = { fg = aspects.leaf, bg = aspects.raven, bold = true },
    IncSearch = { fg = aspects.coal, bg = aspects.bright_orange },
    Italic = { italic = true },
    Keyword = vim.tbl_extend("force", { fg = aspects.moss }, opts.styles.keywords),
    Label = { fg = aspects.snow },
    LineNr = { fg = aspects.slate },
    Macro = { fg = aspects.leaf },
    MatchParen = vim.tbl_extend(
      "force",
      { fg = aspects.bud, bg = aspects.raven, underline = true },
      opts.styles.match_paren
    ),
    MatchParenCur = { underline = true },
    MatchWord = { underline = true },
    MatchWordCur = { underline = true },
    ModeMsg = { fg = aspects.frost, bg = aspects.raven },
    MoreMsg = { fg = aspects.leaf },
    MsgArea = {
      fg = aspects.frost,
      bg = background,
    },
    MsgSeparator = { fg = aspects.frost, bg = aspects.raven },
    NonText = { fg = aspects.frost },
    Normal = {
      fg = aspects.frost,
      bg = background,
    },
    NormalFloat = {
      bg = opts.transparent and aspects.none or aspects.coal,
      -- bg = aspects.coal,
    },
    NormalNC = {
      fg = aspects.frost,
      bg = background,
    },
    Number = { fg = aspects.bark },
    Operator = { fg = aspects.lichen },
    Pmenu = { fg = aspects.gravel, bg = aspects.shade },
    PmenuMatchSel = { bg = aspects.yellow, fg = aspects.slate, reverse = true },
    PmenuSbar = { bg = aspects.coal },
    PmenuSel = { bg = aspects.bud, fg = aspects.slate, reverse = true },
    PmenuThumb = { bg = aspects.slate },
    PreCondit = { fg = aspects.ash },
    PreProc = { fg = aspects.snow },
    Question = { fg = aspects.leaf },
    QuickFixLine = { bg = aspects.shade },
    Repeat = { fg = aspects.moss },
    Search = { fg = aspects.bright_orange, bg = aspects.coal },
    SignColumn = { bg = background },
    Special = { fg = aspects.snow },
    SpecialChar = { fg = aspects.stone },
    SpecialComment = vim.tbl_extend(
      "force",
      { fg = aspects.ash },
      opts.styles.comments
    ),
    SpecialKey = { fg = aspects.green },
    SpellBad = { sp = aspects.error, undercurl = true },
    SpellCap = { sp = aspects.yellow, undercurl = true },
    SpellLocal = { sp = aspects.sign_add, undercurl = true },
    SpellRare = { sp = aspects.purple, undercurl = true },
    Statement = { fg = aspects.moss },
    StorageClass = { fg = aspects.moss },
    String = { fg = aspects.stone },
    Structure = { fg = aspects.moss },
    Substitute = { fg = aspects.coal, bg = aspects.bright_orange },
    TabLine = { fg = aspects.slate, bg = background },
    TabLineFill = { fg = aspects.snow, bg = background },
    TabLineSel = { fg = aspects.snow, bg = background },
    Tag = { fg = aspects.bud },
    TermCursor = {
      fg = aspects.cursor_fg,
      bg = aspects.cursor_bg,
      reverse = false,
    },
    TermCursorNC = {
      fg = aspects.coal,
      reverse = false,
    },
    Title = { fg = aspects.green },
    Todo = { fg = aspects.bark, bg = aspects.raven, bold = true },
    Type = vim.tbl_extend("force", { fg = aspects.snow }, opts.styles.type),
    Typedef = { fg = aspects.snow },
    Underlined = { underline = true },
    Variable = vim.tbl_extend("force", { fg = aspects.snow }, opts.styles.variables),
    VertSplit = { fg = aspects.raven, bg = aspects.shade },
    Visual = { bg = aspects.slate },
    VisualNOS = { bg = aspects.coal },
    WarningMsg = { fg = aspects.yellow, bg = aspects.raven },
    Whitespace = { fg = aspects.slate },
    WildMenu = { fg = aspects.bud, bg = aspects.coal },
    WinBar = {
      bg = background,
      cterm = {
        bold = false,
      },
      fg = aspects.pebble,
    },
    WinBarNC = {
      bg = background,
      cterm = {
        bold = true,
      },
      fg = aspects.ash,
    },
    WinSeparator = {
      fg = aspects.ash,
      bg = background,
    },
  }
end

return M
