local M = {}

function M.highlight(aspects, opts)
  return {
    Normal = {
      fg = aspects.frost,
      bg = opts.transparent and aspects.none or aspects.raven,
    },
    SignColumn = { bg = opts.transparent and aspects.none or aspects.raven },
    MsgArea = {
      fg = aspects.frost,
      bg = opts.transparent and aspects.none or aspects.raven,
    },
    ModeMsg = { fg = aspects.frost, bg = aspects.raven },
    MsgSeparator = { fg = aspects.frost, bg = aspects.raven },
    SpellBad = { sp = aspects.error, undercurl = true },
    SpellCap = { sp = aspects.yellow, undercurl = true },
    SpellLocal = { sp = aspects.sign_add, undercurl = true },
    SpellRare = { sp = aspects.purple, undercurl = true },
    NormalNC = {
      fg = aspects.frost,
      bg = opts.transparent and aspects.none or aspects.raven,
    },
    Pmenu = { fg = aspects.light_gray, bg = aspects.accent },
    PmenuSel = { bg = aspects.light_green, fg = aspects.gray, reverse = true },
    PmenuMatchSel = { bg = aspects.yellow, fg = aspects.gray, reverse = true },
    WildMenu = { fg = aspects.light_green, bg = aspects.alt_bg },
    CursorLineNr = {
      fg = aspects.light_gray,
      bold = true,
    },
    Comment = vim.tbl_extend(
      "force",
      { fg = aspects.medium_gray },
      opts.styles.comments
    ),
    Folded = { fg = aspects.light_gray, bg = aspects.alt_bg },
    FoldColumn = { fg = aspects.light_gray, bg = aspects.alt_bg },
    LineNr = { fg = aspects.gray },
    Whitespace = { fg = aspects.gray },
    VertSplit = { fg = aspects.raven, bg = aspects.accent },
    CursorLine = {
      bg = aspects.alt_bg,
    },
    CursorColumn = { bg = aspects.alt_bg },
    ColorColumn = { bg = aspects.alt_bg },
    NormalFloat = {
      bg = opts.transparent and aspects.none or aspects.alt_bg,
    },
    Visual = { bg = aspects.gray },
    VisualNOS = { bg = aspects.alt_bg },
    WarningMsg = { fg = aspects.yellow, bg = aspects.raven },
    DiffAdd = { bg = aspects.accent_green },
    DiffText = { fg = aspects.frost, bg = aspects.accent_lighter_blue },
    Changed = {
      fg = aspects.sign_change,
    },
    DiffChange = {
      fg = aspects.sign_change,
      bg = aspects.accent_blue,
    },
    DiffDelete = { fg = aspects.sign_delete, bg = aspects.accent_red },
    QuickFixLine = { bg = aspects.accent },
    PmenuSbar = { bg = aspects.alt_bg },
    PmenuThumb = { bg = aspects.light_gray },
    MatchWord = { underline = true },
    MatchParen = vim.tbl_extend(
      "force",
      { fg = aspects.light_green, bg = aspects.raven, underline = true },
      opts.styles.match_paren
    ),
    MatchWordCur = { underline = true },
    MatchParenCur = { underline = true },
    Cursor = { fg = aspects.cursor_fg, bg = aspects.cursor_bg },
    lCursor = { fg = aspects.cursor_fg, bg = aspects.cursor_bg },
    CursorIM = { fg = aspects.cursor_fg, bg = aspects.cursor_bg },
    TermCursor = {
      fg = aspects.cursor_fg,
      bg = aspects.cursor_bg,
      reverse = false,
    },
    TermCursorNC = {
      fg = aspects.alt_bg,
      reverse = false,
    },
    Conceal = { fg = aspects.frost },
    Directory = { fg = aspects.green },
    SpecialKey = { fg = aspects.green },
    Title = { fg = aspects.green },
    ErrorMsg = { fg = aspects.error, bg = aspects.raven, bold = true },
    Search = { fg = aspects.magenta, bg = aspects.alt_bg },
    IncSearch = { fg = aspects.alt_bg, bg = aspects.magenta },
    Substitute = { fg = aspects.alt_bg, bg = aspects.magenta },
    MoreMsg = { fg = aspects.leaf },
    Question = { fg = aspects.leaf },
    EndOfBuffer = { fg = aspects.gray },
    NonText = { fg = aspects.frost },
    Variable = vim.tbl_extend("force", { fg = aspects.white }, opts.styles.variables),
    String = { fg = aspects.stone },
    Character = { fg = aspects.green },
    Constant = { fg = aspects.white },
    Number = { fg = aspects.bark },
    Boolean = { fg = aspects.bark },
    Float = { fg = aspects.bark },
    Identifier = { fg = aspects.white },
    Function = vim.tbl_extend("force", { fg = aspects.leaf }, opts.styles.functions),
    Operator = { fg = aspects.faded_green },
    Type = vim.tbl_extend("force", { fg = aspects.white }, opts.styles.type),
    StorageClass = { fg = aspects.moss },
    Structure = { fg = aspects.moss },
    Typedef = { fg = aspects.white },
    Keyword = vim.tbl_extend("force", { fg = aspects.moss }, opts.styles.keywords),
    Statement = { fg = aspects.moss },
    Conditional = { fg = aspects.moss },
    Repeat = { fg = aspects.moss },
    Label = { fg = aspects.white },
    Exception = { fg = aspects.bark },
    Include = { fg = aspects.bark },
    PreProc = { fg = aspects.white },
    Define = { fg = aspects.bark },
    Macro = { fg = aspects.leaf },
    PreCondit = { fg = aspects.medium_gray },
    Special = { fg = aspects.white },
    SpecialChar = { fg = aspects.stone },
    Tag = { fg = aspects.light_green },
    Debug = { fg = aspects.bark },
    Delimiter = { fg = aspects.white },
    SpecialComment = vim.tbl_extend(
      "force",
      { fg = aspects.medium_gray },
      opts.styles.comments
    ),
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = aspects.leaf, bg = aspects.raven, bold = true },
    Todo = { fg = aspects.bark, bg = aspects.raven, bold = true },
    Error = { fg = aspects.error, bg = aspects.raven, bold = true },
    TabLine = { fg = aspects.gray, bg = aspects.none },
    TabLineSel = { fg = aspects.white, bg = aspects.none },
    TabLineFill = { fg = aspects.white, bg = aspects.none },
    WinSeparator = { fg = aspects.medium_gray, bg = aspects.raven },
    DiagnosticFloatingError = { fg = aspects.error },
    FloatBorder = { fg = aspects.light_gray },
    BufferLineBufferSelected = {
      bold = true,
      cterm = {
        bold = true,
        italic = true,
      },
      default = true,
      -- bg = opts.transparent and aspects.none or aspects.raven,
      bg = aspects.none,
      fg = aspects.frost,
      italic = false,
    },
    gitCommitSummary = { fg = aspects.frost },
    gitCommitHeader = { fg = aspects.medium_gray },
    gitCommitComment = { fg = aspects.medium_gray },
    gitCommitSelectedFile = { fg = aspects.faded_green },
    gitCommitSelectedType = { fg = aspects.faded_green },
    gitCommitDiscardedFile = { fg = aspects.stone },
    gitCommitDiscardedType = { fg = aspects.stone },
    CurSearch = {
      bg = aspects.magenta,
      ctermbg = 11,
      ctermfg = 0,
      fg = aspects.raven,
    },
  }
end

return M
