local M = {}

---@param palette Colors
function M.highlight(palette, opts)
  return {
    ["@annotation"] = { fg = palette.fg1 },
    ["@attribute"] = { fg = palette.fg1 },
    ["@boolean"] = { fg = palette.bark },
    ["@character"] = { fg = palette.green },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { fg = palette.bg0, bg = palette.dark_red, bold = true },
    ["@comment.note"] = { fg = palette.bg0, bg = palette.bg6, bold = true },
    ["@comment.todo"] = { fg = palette.bg0, bg = palette.todo, bold = true },
    ["@comment.warning"] = { fg = palette.bg0, bg = palette.dark_yellow, bold = true },
    ["@const.builtin"] = { fg = palette.bark },
    ["@const.macro"] = { fg = palette.leaf },
    ["@constant"] = { fg = palette.fg1 },
    ["@constant.builtin"] = { fg = palette.mist },
    ["@constructor"] = { fg = palette.leaf },
    ["@constructor.lua"] = { fg = palette.fg2 },
    ["@diff.delta"] = {
      fg = palette.moss,
      bg = palette.accent_blue,
      bold = true,
    },
    ["@error"] = { fg = palette.error },
    ["@function"] = { fg = palette.leaf },
    ["@function.builtin"] = { fg = palette.leaf },
    ["@function.macro"] = { fg = palette.leaf },
    ["@function.method"] = { fg = palette.leaf },
    ["@function.method.call"] = { fg = palette.leaf },
    ["@keyword"] = { fg = palette.moss },
    ["@keyword.conditional"] = { fg = palette.moss },
    ["@keyword.coroutine"] = { fg = palette.moss },
    ["@keyword.exception"] = { fg = palette.bark },
    ["@keyword.function"] = { fg = palette.moss },
    ["@keyword.import"] = { fg = palette.bark },
    ["@keyword.operator"] = { fg = palette.moss },
    ["@keyword.repeat"] = { fg = palette.moss },
    ["@label"] = { fg = palette.fg1 },
    ["@lsp.mod.defaultLibrary"] = { fg = palette.leaf },
    ["@lsp.type.comment"] = {},
    ["@markup"] = { fg = palette.fg1 },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = palette.mist },
    ["@markup.list"] = { fg = palette.fg1 },
    ["@markup.list.unchecked"] = { fg = palette.fg1 },
    ["@markup.literal"] = { fg = palette.fog },
    ["@markup.strong"] = { bold = true },
    ["@markup.title"] = { fg = palette.fog },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = palette.moss },
    ["@module"] = { fg = palette.fg1 },
    ["@number"] = { fg = palette.bark },
    ["@number.float"] = { fg = palette.bark },
    ["@operator"] = { fg = palette.fg2 },
    ["@property"] = { fg = palette.fg1 },
    ["@punctuation.bracket"] = { fg = palette.fg2 },
    ["@punctuation.delimiter"] = { fg = palette.fg2 },
    ["@punctuation.special"] = { fg = palette.fg2 },
    ["@string"] = { fg = palette.stone },
    ["@string.escape"] = { fg = palette.stone },
    ["@string.regexp"] = { fg = palette.stone },
    ["@string.special.path"] = { fg = palette.fg3 },
    ["@string.special.symbol"] = { fg = palette.fog },
    ["@tag"] = { fg = palette.moss },
    ["@tag.attribute"] = { fg = palette.fg1 },
    ["@tag.delimiter"] = { fg = palette.fg1 },
    ["@text.uri"] = { fg = palette.fg3 },
    ["@type"] = { fg = palette.mist },
    ["@type.builtin"] = { fg = palette.mist },
    ["@variable"] = { fg = palette.fg1 },
    ["@variable.builtin"] = { fg = palette.fg1 },
    ["@variable.field"] = { fg = palette.fg1 },
    ["@variable.parameter"] = { fg = palette.fg1 },
    ["@variable.parameter.reference"] = { fg = palette.fg1 },
  }
end

return M
